### ISSUE TITLE
UMD dist

### ISSUE THREAD

**Issue by methyl** [yahoo/react-dnd-touch-backend#10]
Currently there is no UMD dist for users without NPM. I find it very useful as not everyone is able to use NPM module. Thoughts?

**Comment by longlho** [comment]
yeah sure :+1:

**Comment by longlho** [comment]
@methyl I was lookin at this and I think I can release a UMD browserified version. The current `dist` right now doesn't have any dependencies (since it relies on NPM for dep resolving). Thoughts?

**Comment by methyl** [comment]
Sounds great to me :+1:
W dniu wt., 1.12.2015 o 23:36 Long Ho <notifications@github.com> napisał(a):

**Comment by longlho** [comment]
close via e9820c273e1e81aab79f7acbca1e58ae2001f6e3
