### ISSUE TITLE
Client Offset in beginDrag

### ISSUE THREAD

**Issue by 0815Strohhut** [yahoo/react-dnd-touch-backend#111]
Hello,

with Release 6.0 react-dnd supports the use of the client offset in the beginDrag method. (See https://github.com/react-dnd/react-dnd/releases/tag/v6.0.0 [Patch] - Fire off an initCoords event before dragStart to improve client offset-calculation logic.(#1082)). 
In order to support that change, the respective backend has to call the action "initCoords" before "beginDrag". As far as I can tell, this isn't done in the touch backend yet, thus the client offset is null in the begin drag. A similar approch as done for the html5 backend in react dnd solves the issue for the touch backend.

**Comment by longlho** [comment]
thanks for reporting. PR's always welcome 😄
