### ISSUE TITLE
Not support the latest version of react-dnd, i.e. 7.0.2

### ISSUE THREAD

**Issue by EvoqueM** [yahoo/react-dnd-touch-backend#113]
The error message is 
![image](https://user-images.githubusercontent.com/45473833/49423429-756bec00-f7d2-11e8-87dd-26a468f32295.png)
 
And `react-dnd 6.0.0` works fine with `react-dnd-touch-backend 0.6.0`.

Do you guys have plan to keep up with `react-dnd`?  tks...

**Comment by longlho** [comment]
fixed in v0.7
