### ISSUE TITLE
this.actions.initCoords is not a function

### ISSUE THREAD

**Issue by willnix86** [yahoo/react-dnd-touch-backend#114]
Whenever I try to drag a draggable object, I receive the following error:

Touch.js:542 Uncaught TypeError: this.actions.initCoords is not a function
    at TouchBackend.handleTopMove (Touch.js:542)
handleTopMove @ Touch.js:542

Any ideas for a fix?

**Comment by longlho** [comment]
fixed in v0.7

**Comment by willnix86** [comment]
Thanks. I'm sure I'm being stupid but I seem to be stuck on v0.6 with react-dnd-touch-backend. When I try to install it again, I get this in my terminal:

npm WARN react-dnd-touch-backend@0.6.0 requires a peer of react-dnd@^6.0.0 but none is installed. You must install peer dependencies yourself.

+ react-dnd-touch-backend@0.6.0
updated 1 package and audited 36062 packages in 16.801s
found 0 vulnerabilities

Shouldn't it install 0.7?

**Comment by longlho** [comment]
https://www.npmjs.com/package/react-dnd-touch-backend has latest version as 0.7. Maybe clear your npm cache, package-lock or force install `npm i react-dnd-touch-backend@0.7`

**Comment by willnix86** [comment]
That worked. Still getting the same initCoords error though. Is it something to do with the fact that it's not recognizing react-dnd? I have both installed but the latter isn't registering as the peer for touch-dnd

npm WARN react-dnd-touch-backend@0.7.0 requires a peer of react-dnd@^6.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by longlho** [comment]
oh sorry that was my bad. try `0.7.1`

**Comment by willnix86** [comment]
That's fixed the 'peer' issue, but I still see the initCoords error

**Comment by longlho** [comment]
hmm can u make sure u clear all ur caches? It shouldn't be there anymore

**Comment by willnix86** [comment]
Ignore me, works great!
