### ISSUE TITLE
Links in docs not working

### ISSUE THREAD

**Issue by bastaware** [yahoo/react-dnd-touch-backend#116]
From docs:

Drag Preview
Since native Drag-n-Drop is not currently supported in touch devices. A custom DragPreview is required. Check out the example for a sample implementation.

Link to example and DragPreview does not work.

**Comment by frankbolviken** [comment]
Yep, Links not working.. and I'm currently looking for this. Any ideas?

**Comment by Palaklive** [comment]
Hey @bastaware @frankbolviken 
May be this [custom-drag-layer example](https://react-dnd.github.io/react-dnd/examples/drag-around/custom-drag-layer) will be helpful to you.
