### ISSUE TITLE
Babel "Duplicate plugin/preset detected" error message

### ISSUE THREAD

**Issue by louh** [yahoo/react-dnd-touch-backend#119]
I'm using Babel and Parcel to build my application. With `react-dnd-touch-backend`, I'm getting this error:

```
🚨  /Users/lou/Repositories/streetmix/streetmix/node_modules/react-dnd-touch-backend/dist/Touch.js: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]
```

**Comment by louh** [comment]
It seems that the `.babelrc` in the package root is being published, which is being detected by Babel, and then it conflicts with my own project's `.babelrc`. Since the package is already transpiled when it's published, you don't need to include `.babelrc` in the distribution. The best option is to add `.babelrc` to `.npmignore`.

**Comment by VojGin** [comment]
Confirmed, after removing .babelrc from react-dnd-touch-backend manually, it works again like a charm.

Please consider removing .babelrc from the repo
