### ISSUE TITLE
Warning: setState(...): Cannot update during an existing state transition

### ISSUE THREAD

**Issue by hakunin** [yahoo/react-dnd-touch-backend#19]
Hi, I am getting

> warning.js?8a56:45 Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

Any ideas? I am sorting stuff while you're dragging an item so that might be the cause.
The code is based on official guide on how to do sortable, and the problem began when I switched backends.

**Comment by longlho** [comment]
do u have a code sample by any chance?

**Comment by hakunin** [comment]
Too much code, will reopen when I have more info.
