### ISSUE TITLE
Decorators are not supported yet in 6.x pending proposal update.

### ISSUE THREAD

**Issue by esseb** [yahoo/react-dnd-touch-backend#25]
Checking out the repo (hash 6d8cf69ac74c55371f8c8c59467fab9399e6430f) and running `npm i && gulp js-dev` as recommended in README.md I get this error:
```js
[13:18:42] { [SyntaxError: /Users/esseb/Repositories/react-dnd-touch-backend/examples/js/ItemPreview.jsx: Decorators are not supported yet in 6.x pending proposal update. while parsing file: /Users/esseb/Repositories/react-dnd-touch-backend/examples/js/ItemPreview.jsx]
  loc: Position { line: 40, column: 15 },
```

I solved it locally by installing `npm i --save-dev babel-plugin-transform-decorators-legacy` and adding `"plugins": [["transform-decorators-legacy"]}` to `.babelrc`.

I'm not submitting a pull request since I don't know if using the decorator legacy plugin is how you want to solve this. This issue might help others encountering the same issue, however.

**Comment by longlho** [comment]
ah kk tks for reporting! feel free to PR to remove the decorators :) It'll take me a while to get to it :(

**Comment by esseb** [comment]
@longlho so you want to use ES6 style `export default DragLayer(collect)(ItemPreview)` instead of decorators?

I could do it, if I find the time :), just want to make sure that's how you would like it solved.

**Comment by longlho** [comment]
yeah that sounds good :)

**Comment by longlho** [comment]
should be fixed
