### ISSUE TITLE
preview doesn't work

### ISSUE THREAD

**Issue by railty** [yahoo/react-dnd-touch-backend#3]
can you confirm that preview doesn't work?

**Comment by longlho** [comment]
Checked on iOS and it works, does it not work on Android for u?

**Comment by longlho** [comment]
@railty any clarification?

**Comment by svntastic** [comment]
I can confirm that preview is not working on Android. Drag works correctly, but you can't see what's being dragged.

**Comment by longlho** [comment]
Ah kk gotcha, on touch devices native Drag-n-Drop actually does not get triggered, so a custom DragPreview is required. I'll put a note in the README and reference this issue.

**Comment by railty** [comment]
that explains, good job
