### ISSUE TITLE
"Shallow" isOver doesn't work correctly on nested targets 

### ISSUE THREAD

**Issue by glenn-allen** [yahoo/react-dnd-touch-backend#30]
As per this example:  [https://github.com/glenn-allen/dnd-touch-example](https://github.com/glenn-allen/dnd-touch-example)
And the discussion here: https://github.com/yahoo/react-dnd-touch-backend/issues/14
The drop target's ```monitor.isOver({ shallow: true })``` doesn't work correctly for nested or overlapping drop targets.

I realise there's some suggestions that the issue is occurring within the React DnD library itself & that determining true stacking order might not be possible, but just posting here in case somebody (or we) find a fix.
The previous issue was closed with a workaround that avoided the need for monitor.isOver rather than actually finding a fix for it.
@isaacwilliams will probably handle any follow ups if there are updates.  Thanks

**Comment by krtr** [comment]
I think I have fixed stacking order, hover is working but drop event is fired to all components under cursor so its need some more work.
But you can take a look: https://github.com/krtr/react-dnd-touch-backend/blob/targets-sort/src/Touch.js#L248

**Comment by glenn-allen** [comment]
Hi guys,

Sorry I've only just come back from holiday so I just tested the merge and it fixes the `isOver` issue.  Thanks so much!!

@krtr I haven't tried your change yet, but that method `elementFromPoint` is awesome!  Amazed I hadn't heard it / found it earlier.

Thanks again everyone, closing this now.

**Comment by Venryx** [comment]
The call order for canDrop and drop seem to be off for me, even in the newer version.

Layout's like this:
<ScriptUI ref="outer">
    <ScriptUI ref="inner"/>
</ScriptUI>

And the ScriptUI class has a @DropTarget decorator.

Problem is that:
* The canDrop and drop functions get called on the outer component first.
* The targetId for the outer one is higher than the targetId for the inner one. (outer is 61, inner is 57)
* When I (for debugging) call `monitor.internalMonitor.getTargetIds()`, it lists ["T57", "T61"], which results in `monitor.getOver({shallow: true})` returning true only for the outer component.

In other words, react-dnd thinks the outer component is the inner component (or something), so the drops always succeed for the outer one.

For now, I use this really bad hack in the ScriptUI's canDrop function:
```
var dropTarget = monitor.GetTargetComponent();
var deepestDropTargetOver = monitor.internalMonitor.GetTargetComponents().Max(a=>a.props.script.GetPath_Absolute().nodes.length);
if (deepestDropTargetOver != dropTarget) return;
```

Note the use of some custom functions in the above. For the GetTargetComponent() and GetTargetComponents() functions, I added them to the TargetMonitor and DragDropMonitor classes like-so:
```
g.DragDropMonitor = require("react-dnd/node_modules/dnd-core/lib/DragDropMonitor");
DragDropMonitor.prototype.GetTargetComponents = function GetTargetComponents() {
    return this.getTargetIds().Select(targetID=>this.registry.handlers[targetID].component);
};

var createTargetMonitor = require("react-dnd/lib/createTargetMonitor");
g.TargetMonitor = createTargetMonitor({getMonitor: function() {}}).constructor;
TargetMonitor.prototype.GetTargetComponent = function() {
    return this.internalMonitor.registry.handlers[this.targetId].component;
};
```

I know many devs frown on this kind of thing, but thought I'd mention the workaround that I'm currently using.
