### ISSUE TITLE
Dragging over and dropping to drop targets don't work anymore

### ISSUE THREAD

**Issue by astashov** [yahoo/react-dnd-touch-backend#34]
It seems like because the code for figuring out the matching targets was commented out: https://github.com/yahoo/react-dnd-touch-backend/blob/master/src/Touch.js#L259
And browsers don't fire touchmove/touchend events on a node if the touch was not originated on the node.

Rolling back to 0.2.7 solves the issue.

**Comment by longlho** [comment]
cc @DetweilerRyan

**Comment by badtant** [comment]
Also seeing this issue

**Comment by SDSLeon** [comment]
Yeap, if dropTarget overlapped by children its not work;

**Comment by tuckermiller** [comment]
I'm not sure I understand, is this issue that dragging and dropping to any drop target, period, won't work? Basically making the current version of the touch backend unusable? Or is it a more specific case. Thanks in advance

**Comment by DetweilerRyan** [comment]
Currently, version 0.3.0 only works for mouse events and not touch events.

**Comment by tuckermiller** [comment]
Gotcha, thank you very much for the quick response! Very much appreciate this library, since I don't need nested children will try 0.2.7

**Comment by DetweilerRyan** [comment]
Yes, I recommend using 0.2.7.

**Comment by badtant** [comment]
Seems to work with 0.3.2

**Comment by swhite24** [comment]
0.3.2 works for me as well 👍

**Comment by JoaoMosmann** [comment]
Seems to be working :smile:

**Comment by mmairs9** [comment]
i see the same issue in the latest version 0.3.21 rolling back all the way to 0.2.7 solved the issue. The hover only triggered when the mouse left the preview when dragging quickly.
