### ISSUE TITLE
Permission denied to access property "targetTouches"

### ISSUE THREAD

**Issue by hakunin** [yahoo/react-dnd-touch-backend#36]
I get this one from time to time from Firefox users and have gotten it myself, although I couldn't reproduce it.

Then it seems to be followed by these two:
TypeError: Cannot read property 'getNativeNode' of null
TypeError: Cannot read property '_currentElement' of null

On my page I don't have any iframes and my FF is pretty stock apart from firebug. 
In 20 minutes of playing with the page I couldn't reproduce it but I get it almost daily from people who use FF.

Any ideas?

It seems to be from the family of cross domain errors:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied

**Comment by JoaoMosmann** [comment]
Hi @hakunin. Sorry for the delay. Have you worked it around?

Did you find a way to reproduce it ?

Cheers

**Comment by hakunin** [comment]
I haven't worked on it, as it doesn't break anything for the users. We can close it and when someone is able to, they can provide more info.

**Comment by JoaoMosmann** [comment]
Seems good to me. Thanks
