### ISSUE TITLE
usage of redux connect and react-dnd-touch-backend

### ISSUE THREAD

**Issue by longmfe** [yahoo/react-dnd-touch-backend#39]
I got an issue with using redux connect. It works for html5-backend. But when I switch to touch-backend. I can not drag the item actually. Is there anyone met this kind of issue? 
I did something like this
`import { connect } from "react-redux";`
`import TouchBackend from "react-dnd-touch-backend";`
`import { DragDropContext } from "react-dnd";`

`class App extends Component {`
  `...`
`}`

`App = DragDropContext(TouchBackend)(App);`
`export default connect(mapStateToProps)(App);`

**Comment by longlho** [comment]
this only handles touch event. By drag do u mean w/ a mouse?

**Comment by longmfe** [comment]
Thanks for reminding. It actually works on my real phone. But it doesn't work when I try to test it on chrome with mobile mode. Since I use mouse to simulate touch event. Thanks.
