### ISSUE TITLE
Example not working 

### ISSUE THREAD

**Issue by cagarweyne** [yahoo/react-dnd-touch-backend#40]
I've tried to run the example and pushed to a github page to see it in action on touch devices, but the drag and drop is not working properly:

https://cagarweyne.github.io/touch/

I've basically followed the steps for building the example from the repo, maybe I'm missing something?

**Comment by platvampb** [comment]
Same here. Wonder if this is related to #34

**Comment by HugoMcPhee** [comment]
It's working for me if I drag onto the text of another item.
Have you tried adding a background color to each item in the list? 
It might not be detecting touches on the fully transparent parts of the item
