### ISSUE TITLE
Broken w/ React-DND 2

### ISSUE THREAD

**Issue by mereskin** [yahoo/react-dnd-touch-backend#5]
Looks like https://github.com/yahoo/react-dnd-touch-backend/commit/ef81ac2798328a60b89b7d90409144ab629127e5 fixes this problem. Any chance you can release `0.2.0`, @longlho ?

**Comment by longlho** [comment]
yeah sure :)

**Comment by longlho** [comment]
done :) lmk if u see any issues

**Comment by longlho** [comment]
oh kk will release `0.2.0` w/ the React 14 stuff & react-dnd@2.0.0 also

**Comment by longlho** [comment]
`0.2.0` should be published

**Comment by mereskin** [comment]
Thanks, man!
