### ISSUE TITLE
FileDropZone with touch backend

### ISSUE THREAD

**Issue by pitrackster** [yahoo/react-dnd-touch-backend#54]
Hi there and thanks for your work... Very usefull !

I was wondering about this : https://react-dnd.github.io/react-dnd/docs-faq.html#112 

#### How do I register a drop target for the native files?

> If you are using the HTML5 backend, you can register a drop target for one of the NativeTypes it exports

But what if we use `TouchBackend` ?

Thanks

**Comment by JoaoMosmann** [comment]
It's not possible. Only the native drag n' drop API allows you to drag things from outside your application.
