### ISSUE TITLE
Dynamic nested DropTargets drop method order is not tied to DOM element depth

### ISSUE THREAD

**Issue by JoaoMosmann** [yahoo/react-dnd-touch-backend#56]
I migrating from the HTML5 backend and I got stuck with this problem.

I have 2 DropTargets, one inside the other. The top level one filters the dropped source and makes some changes and return a modified object in the drop method. So the bottom level DropTarget process the final result.

This was possible with the HTML5 backend because the drag n' drop backend ensured the order.

It was working with the touch backend until this pull request #37 

In this pull request, the event handling was moved to the window. So the order of the drop calls is based on the first to attach the event, to the last. It usually works, but with I have dynamic nested DropTargets, it gets messy.

I will do a PR with an example that reproduces the problem.

**Comment by JoaoMosmann** [comment]
I added a PR with a example to test the problem and a solution as well #57

**Comment by longlho** [comment]
thanks :)
