### ISSUE TITLE
Version 0.3.7 doesn't work on iOS

### ISSUE THREAD

**Issue by calrsom** [yahoo/react-dnd-touch-backend#58]
This line https://github.com/yahoo/react-dnd-touch-backend/commit/c210e11a499928e11a577d3decfd1ebc38341a10#diff-694049bbccadc234052edce94ace9cbcR335 breaks on iOS because `Document.elementsFromPoint()` is not available on Safari.  See: https://developer.mozilla.org/en-US/docs/Web/API/Document/elementsFromPoint.

**Comment by JasonBoy** [comment]
same problem

**Comment by longlho** [comment]
ping @JoaoMosmann ^^

**Comment by JoaoMosmann** [comment]
My bad, sorry. I was sure that `elementsFromPoint` was supported everywhere. Even IE10 supports it. I'll work around it and commit.

**Comment by JoaoMosmann** [comment]
@calrsom I added a pull request with a polyfill for when the function `document.elementsFromPoint` is not available. I've tested it in every major browser but Safari, so if you could do it, it would be great.

**Comment by longlho** [comment]
0.3.8 published that should address this

**Comment by calrsom** [comment]
We have tested 0.3.8 and it appears to work.  Thanks!
