### ISSUE TITLE
Touch backend differs from HTML5 backend in "list to list"?

### ISSUE THREAD

**Issue by bebraw** [yahoo/react-dnd-touch-backend#6]
I'm current in the process of porting my [kanban application](https://github.com/survivejs/webpack_react/tree/touch_dnd) to react-dnd-touch-backend. I've managed to get most of it sorted out myself. There's only one major problem remaining.

Something very strange happens when I drag a note from a lane to lane. It attaches the note to the target lane but goes completely unresponsive after that. If you release a note, it will get attached to that specific lane. Note that everything goes fine on desktop.

Is there some good way to debug the touch backend using a desktop browser? If so, I can probably get some useful debug information for you. Hopefully that will help us to understand where the problem is and resolve it.

**Comment by longlho** [comment]
@bebraw is this this [one](https://github.com/survivejs/webpack_react/tree/master/project_source/07_implementing_dnd) I'll take a quick look tonite :)

On Chrome u can enable touch emulation and step thru the process. Does the behavior appear after the note just arrived in the 2nd lane?

**Comment by bebraw** [comment]
@longlho See [here](https://github.com/survivejs/webpack_react/tree/touch_dnd/project_source/07_implementing_dnd/kanban_app).

Thanks for the tip. I managed to make it crash!

```
Uncaught TypeError: Cannot read property 'parentElement' of undefined - Touch.js
```

The line where it crashes looks like this

```
this.draggedSourceNodeRemovalObserver.observe(node.parentElement, { childList: true });
```

This happens right after you drag a note to another lane. You'll need to set up some initial data of course.

**Comment by longlho** [comment]
ha kk thanks I'll try to replicate and fix it hopefully tonite :)

**Comment by longlho** [comment]
@bebraw sorry I have not forgotten, just been very busy :(

**Comment by bebraw** [comment]
@longlho No hurry. Please take your time. :)

**Comment by longlho** [comment]
@bebraw I updated the examples to support multi lists couldn't replicate the issue so u mind taking a quick look at the new examples :) ?

**Comment by bebraw** [comment]
Thanks. I'll have a good look in a day or two (traveling atm).

**Comment by bebraw** [comment]
Hi,

I found a little issue at your demo. If I drag an item to its original place, it yields

```
Dragged 3 in list 0 to 3 in list 0
warning.js:45 Warning: flattenChildren(...): Encountered two children with the same key, `.$3`. Child keys must be unique; when two children share a key, only the first child will be used.warning @ warning.js:45instantiateChild @ ReactChildReconciler.js:26traverseAllChildrenImpl @ traverseAllChildren.js:98traverseAllChildrenImpl @ traverseAllChildren.js:114traverseAllChildren @ traverseAllChildren.js:186ReactChildReconciler.instantiateChildren @ ReactChildReconciler.js:52ReactMultiChild.Mixin._reconcilerInstantiateChildren @ ReactMultiChild.js:197ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:232ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:241ReactDOMComponent.Mixin._createContentMarkup @ ReactDOMComponent.js:592ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:482ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:225wrapper @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:37mountComponentIntoNode @ ReactMount.js:266Mixin.perform @ Transaction.js:136batchedMountComponentIntoNode @ ReactMount.js:282Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:94ReactMount._renderNewRootComponent @ ReactMount.js:476wrapper @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:545ReactMount.render @ ReactMount.js:565wrapper @ ReactPerf.js:66render @ index.js:68reorder @ index.js:50drop @ DraggableItem.jsx:31drop @ createTargetFactory.js:68(anonymous function) @ dragDrop.js:154drop @ dragDrop.js:151(anonymous function) @ DragDropManager.js:74handleTopTouchEndCapture @ Touch.js:198
```

I still have to compare your implementation to mine to see what's the difference. This is something else entirely.

**Comment by longlho** [comment]
yup will fix that one in the demo :) tks for letting me know.

**Comment by longlho** [comment]
@bebraw any luck :)?

**Comment by bebraw** [comment]
@longlho Not yet. I've been busy with some other work but I'll look into it in the near future.

**Comment by longlho** [comment]
@bebraw feel free to reopen this issue if #12 doesn't work for u.
