### ISSUE TITLE
Is there any CHANGELOG for every version?

### ISSUE THREAD

**Issue by JasonBoy** [yahoo/react-dnd-touch-backend#63]
there are no tags or some `changelog.md` file to view the change between every version, can only get some info on `commits`, maybe it's better to add some doc for this, OR is it somewhere else?

**Comment by JoaoMosmann** [comment]
There is none. I'm planning to add tags and a changelog soon.

**Comment by JasonBoy** [comment]
great 👍

**Comment by JoaoMosmann** [comment]
Changelog added at 343f2851d4a9bb6779dc387251f06667d19cea52 :confetti_ball:
