### ISSUE TITLE
Use npm scripts to run `gulp dev`

### ISSUE THREAD

**Issue by scottyeck** [yahoo/react-dnd-touch-backend#65]
... this way users can run `gulp dev` without `gulp` installed globally. 😇

**Comment by longlho** [comment]
I'm actually in favor of hosing `gulp` entirely

**Comment by scottyeck** [comment]
In the meantime... https://github.com/yahoo/react-dnd-touch-backend/pull/66

**Comment by longlho** [comment]
LGTM :) I'll merge once u sign the NDA

**Comment by scottyeck** [comment]
@longlho Pretty sure I just did - never seen that before.

**Comment by longlho** [comment]
oh kk just give the bot some time to refresh then
