### ISSUE TITLE
Touch and mouse support

### ISSUE THREAD

**Issue by esseb** [yahoo/react-dnd-touch-backend#7]
Just checked out the repo and tried the example now. Works fine on mobile with touch, but the example does nothing on desktop with a mouse. Is there a way to get both touch and mouse support working or is this purely for touch devices?

**Comment by bebraw** [comment]
Check if touch is supported and select a backend based on that:

```javascript
import 'browsernizr/test/touchevents';

import Modernizr from 'browsernizr';

import React from 'react';
import ReactDOM from 'react-dom';
import {DragDropContext} from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';
import TouchBackend from 'react-dnd-touch-backend';

...

ReactDOM.render(
  React.createElement(DragDropContext(
    Modernizr.touchevents ? TouchBackend : HTML5Backend)(App)
  ),
  app
);
```

**Comment by esseb** [comment]
So it's either or? I've got a touchscreen Lenovo laptop I primarily use a mouse with.

**Comment by longlho** [comment]
@esseb yeah right now it's either or. There's definitely a possibility for a hybrid but since every touch screen claim to support native dnd it might get hairy.

thanks @bebraw for the clarification.

**Comment by esseb** [comment]
@longlho Well, how about supporting mousedown and mousemove in addition to touchstart/touchmove? I don't necessarily have to use the html5backend with a mouse, if the touch backend supported mouse events.

**Comment by longlho** [comment]
@esseb I'll try to take a look. Native dnd is definitely more performant than manual mouse events, and does not suffer from tricky propagation (e.g A long tap on certain elements (like anchor link) brings up bookmark menu and prevent default/stop propagation will cancel mouse emulation)

**Comment by dshorowitz** [comment]
+1 for supporting both. Would be really useful to not have it be an either/or type thing.

**Comment by longlho** [comment]
addressed in #9

**Comment by esseb** [comment]
@longlho thanks!

**Comment by jrodl3r** [comment]
@bebraw thank you for that solution. however, it doesn't work on isomorphic / server-side render... Modernizr throws: `window is not defined`

any ideas on how to work around that in webpack/SSR env? Thx!

**Comment by bebraw** [comment]
@jrodl3r You could try [shimming window](https://github.com/webpack/docs/wiki/shimming-modules). That should get rid of the error at least.

**Comment by jrodl3r** [comment]
@bebraw I don't think that technique is going to work for the React (SSR) project i'm working with: (https://github.com/reactGo/reactGo ~ https://github.com/reactGo/reactGo/blob/master/app/containers/App.jsx)

When App.jsx is loaded, `window` is never going to be accessible to leverage on a ternary at the point it's executed. I would love to hear otherwise, but the way it's being used for the SSR payload, I'm not optimistic.

I have however initially had some luck using this `{ enableMouseEvents: true }` - Are there any significant drawbacks I'm not aware of use the enableMouseEvents flag? Thx! 🍻

**Comment by longlho** [comment]
@jrodl3r bc `mouse`, `touch` & `draganddrop` API are radically different and bridging them is fairly [buggy](https://github.com/yahoo/react-dnd-touch-backend/issues/26#issuecomment-208098139)

**Comment by jrodl3r** [comment]
@longlho well I sure wish there was a way to detect `Touch Support` and then roll the TouchBackend / HTML5Backend in a Server-Sider Rendered project like the one linked above 👍

**Comment by OliverJAsh** [comment]
`Modernizr.touchevents` returns `true` in desktop Chrome for me. 😒
