### ISSUE TITLE
delayTouchStart timer does not reset when an element is not dragged

### ISSUE THREAD

**Issue by emckay** [yahoo/react-dnd-touch-backend#75]
There is a bug with `delayTouchStart`.

To reproduce:

1. Add `delayTouchStart: 300` to the options in the example on this repo.
2. On a touch device (or Chrome's Device mode), tap one draggable element for more than 300ms.
3. Stop tapping the element without dragging it anywhere.
4. Touch another element, and immediately start dragging.

What happens: 

The second element will be dragged, with its drag preview offset by the difference in the original positions between the first and second elements.

What should happen:

The second element should not be dragged until the delay has elapsed, and the drag preview should be in the correct position.

**Comment by JoaoMosmann** [comment]
Hey @emckay 
Sorry for the delay. So, I'm trying to reproduce this behavior, but I'm having a hard time trying.
Actually, this whole `delayTouchStart` functionality seems to be buggy and unreliable.

I know it's asking too much, but could you do a screencast so I can see how you are doing it?

Thanks a million

**Comment by emckay** [comment]
I don't really see any problems with delayTouchStart after fixing this. We are currently using it in production, and I haven't heard any complaints about it other than this issue :)

Here is a recording, but it's quite hard to see what's going on. This first one is recorded on `master`. The only difference is that I added a 300ms `delayTouchStart` in `examples/index.jsx`.

![before](https://user-images.githubusercontent.com/899325/28041178-45e94844-657d-11e7-97be-037d21685244.gif)

I try several times to drag item 2 without pressing for 300ms (the `delayTouchStart`). Then I press item 2 for a couple seconds and release without moving. I then tap item 13 and before 300ms elapse, I am able to drag the element. The drag preview element is not positioned correctly, but it does drop where I release my finger.

After my proposed fix in #76, here's the behavior:

![after](https://user-images.githubusercontent.com/899325/28041256-919cecb4-657d-11e7-90fd-90bc4ca50a0a.gif)

These were made in the chrome dev tools device mode. Sorry that the gifs are not very clear!
