### ISSUE TITLE
Autoscroll

### ISSUE THREAD

**Issue by igorrKurr** [yahoo/react-dnd-touch-backend#8]
Hi!
Is it possible to setup autoscroll in this, i mean when dragged item reach near bottom/top of container, scroll it?

**Comment by longlho** [comment]
hmm personally I think it might be out of scope. The original `dnd` handles dragging from window to window (file upload drop, e.g)

**Comment by jiglesias** [comment]
Hi!
With HTML5 Backend, react-dnd scrolls automatically.
Do you have any workaround for this feature?

**Comment by wan54** [comment]
+1

**Comment by gulderov** [comment]
You can use https://github.com/azuqua/react-dnd-scrollzone

**Comment by igorrKurr** [comment]
Thanks for comments, actually that is outdated issue, so I'm going to close it

**Comment by amakhrov** [comment]
@igorrKurr by saying it's outdated do you mean it's resolved already? or is there a known workaround (like using react-dnd-scrollzone, as suggested above)?

**Comment by igorrKurr** [comment]
I mean it was resolved.

**Comment by amakhrov** [comment]
@igorrKurr thanks. Still wanted to confirm:

When using the backend with `mouseEvents` enabled, I get the following behavior:
- when dragging an element to the screen edges, no auto-scrolling happens
- however, I'm still able to scroll manually during that - using a mouse wheel (or a scroll gesture on a touchpad).

Is that the expected behavior?

(I know mouseEvents is marked as unstable in the docs :) )

**Comment by igorrKurr** [comment]
@amakhrov Ok, sure:)

Project I've been working on while posting this issue was mobile only (cordova), so I didn't tested it for mouse at all and cannot say how it was behaving with `mouseEvents`.
Generally speaking, I believe that behaviour you've described is expected for touch backend.

**Comment by JoaoMosmann** [comment]
@amakhrov Why don't you use the touch backend when it's on a desktop?

**Comment by amakhrov** [comment]
@JoaoMosmann I assume you mean - why don't I use html5 backend, right?
 
- With html5 backend I was struggling with repaint bugs in Chrome when dragging (found a workaround though: https://github.com/react-dnd/react-dnd/issues/747)
- I do want to support mobiles users as well as desktop.

**Comment by JoaoMosmann** [comment]
Woops. Yes, that what I meant :confounded: 

Currently I'm using both, html5-backend for desktop, and touch for touch devices.

You could do it by doing something like this:

```ts
let isTouchDevice: boolean;
let DNDBackend: any;

// Checks if current device has touch capability
try {
    document.createEvent("TouchEvent");
    isTouchDevice = true;
} catch (err) {
    isTouchDevice = false;
}

if (isTouchDevice) {
    DNDBackend = TouchBackend({ enableMouseEvents: false });
} else {
    DNDBackend = HTML5Backend;
}

export default DragDropContext(DNDBackend)(MyApplication); 
```

**Comment by amakhrov** [comment]
@JoaoMosmann thanks for the hint, I'll try that!

One concern is that it seems to include the both backends into the resulting bundle. Probably need to add some async loading of the backend, which complicates the setup

**Comment by JoaoMosmann** [comment]
Yes, in my case both backends are bundled, but they weight just a little, so I see no problem with having both. But of course, if your application is weight-sensitive, it might be a problem.

**Comment by amakhrov** [comment]
@JoaoMosmann you said you switch between html5 and touch backends based on device capabilities.
How do you implement drag previews in this case? For html5 backend previews are out of the box, while for touch backend you need to define previews manually.
How do you combine this together in a single draggable component?

**Comment by JoaoMosmann** [comment]
Hey @amakhrov. I implement a custom DragLayer that works for both.

You can see an example here:
https://github.com/yahoo/react-dnd-touch-backend/blob/master/examples/js/ItemPreview.jsx

But in my case, that I have many different types of draggable objects, I pass a JSX in the DragAction, and render this JSX inside the DragLayer component. It works for both html5 and touch backends.

**Comment by amakhrov** [comment]
Ah, so you use the same custom preview in the both cases.
Got it, thanks!
