### ISSUE TITLE
isOver never becomes true, hover event never fires after switch from HTML5Backend to Touch

### ISSUE THREAD

**Issue by erubi** [yahoo/react-dnd-touch-backend#90]
Trying to switch to the touch backend after having everything working using HTML5Backend in a table with draggable tr components. The isOver prop never changes and it seems like there's no interaction between any of the components. I've created a preview with DragLayer which works fine but nothing happens when dragging over the trs which are both DragSources and DragTargets.

Would appreciate any advice on why this might be happening and how to fix. Thanks

**Comment by lednhatkhanh** [comment]
Hey, did you find the way to fix the issue? Thanks
