### ISSUE TITLE
If e.button is defined then it should be MouseButton.Left.

### ISSUE THREAD

**Issue by ms88privat** [yahoo/react-dnd-touch-backend#93]
I updated the topic. See comment below

**Comment by delijah** [comment]
We get the following error message with react 16:
```
Uncaught TypeError: Cannot read property 'unshift' of undefined
    at TouchBackend.handleMoveStart (Touch.js?17a0:384)
```

After some investigation, we are a bit surprised that it ever worked. We found the part of code which causes us troubles:

https://github.com/yahoo/react-dnd-touch-backend/blob/b9edb860905487268e3196bd5dc13fc834fc83e6/src/Touch.js#L47

The comment above this line says:
```
// For touch events, button will be undefined. If e.button is defined,
// then it should be MouseButton.Left.
```

IMHO the behaviour which the comment describes would be correct, but then the if statement has been written wrong. The right way would be:
`return e.button === undefined || e.button === MouseButton.Left;`

**Comment by delijah** [comment]
According to my findings, describe in my previous comment, this bug is not related to react 16, but was introduced by version 0.3.18 of react-dnd-touch-backend.

**Comment by longlho** [comment]
It’d be great if u can submit a PR

**Comment by delijah** [comment]
Sorry i was too slow 😳 Thanks to @jedwards1211 for creating a PR to solve this 👍
